#NAME - ANKUSH NAGPAL   ROLL NO - 2018201083

# -*- MakeFile -*-

#target: dependencies
#	action


CC=g++
#all:  homepage ver_overflow


tracker:multi_server.o trackerFunctions.o
	$(CC) -std=c++11 multi_server.o trackerFunctions.o  -o tracker 


multi_server.o:multi_server.cpp
	$(CC) -std=c++11 -c multi_server.cpp tracker.h

tackerFunctions.o:trackerFunctions.cpp
	$(CC) -std=c++11 -c trackerFunctions.cpp

clear:
	rm *.o client 